dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    secure: ukbBlxBowikcLCauAvbWaBQtoSkbsU9xLn4JsA6vDnjRvUWKWY+r2rFIV0DVs6lUml77cN2GQayRX2nTd9KajCrE6X0uc0cpYm6EQtOdhG3wROobe5DWMnDTQhyaeeisxXHNGWk5QJ3Y7cm5Y6+1d0EKVJ6ytXuiG/dgQrxaODcTikCE2cJZFGm1bQunph8M1QwmvwARWTIYbme91NqVUudh74jzDiTeP7GdTrgg1+/RXRwQNXyiRcDms+XT1ERe595oc3t+QyIp+RlWKF2DZngzY2vSXEegzmJ2513XLV9oe/Cs0tqwtIKlJMUOQmA4ij2OXpzwpCme7AIL3ZE9oq2l4RZafFMlgs+Jg21SEXy9aLtwVCEcxs9VWooDePQYJ3kZzDltkVQf2vcm59+zzz+ACcxGdU4YgxbtfhgdGBrJSJbgJ6mEQ+Y9xtrUXneP0jLUIrkI2QhwqSPn9L3cteaemq/tNAx9Pg04JHiSULVB09eSzTUVkHsv/mozm+OgdJyYd5DIVRk353ivMRyqLvV5m5IuBYlR8g8QjgjCPI4WpnYLH90oFsotA9NLQtFyFz84eYhWjR0VIsbZEk3nV4GqV8hK/ODcm+iRzhNHFlUjfKxTAP9CRagHME9ABFU3rW6yaUlQ0k7ok4ohXSMRCtFwVe/MOQqkTFy+ADv/Dmk=
