global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anatoliy_tsaplin'
